name: Update Research Summaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-summaries:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyPDF2 ollama openai jinja2 chromadb

    - name: Install Ollama
      run: |
        curl https://ollama.ai/install.sh | sh
        ollama pull llama2:7b

    - name: Cache ChromaDB
      uses: actions/cache@v2
      with:
        path: ./chroma_persist
        key: ${{ runner.os }}-chromadb-${{ hashFiles('**/research_summarizer.py') }}
        restore-keys: |
          ${{ runner.os }}-chromadb-

    - name: Run research summarizer
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: "gpt-4o-mini"
      run: python research_summarizer.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add weekly_summaries/* chroma_persist
        git commit -m "Update research summaries and ChromaDB" -a || echo "No changes to commit"
        git push